consultingEmail: partnerships-sol@stgallen.oikos-international.org
projectHeadEmail: ph-solar@stgallen.oikos-international.org
contactFormUrl: https://loud-budget-b2d.notion.site/3d9ebcdd83ce802dbff9ccdfaf0e30ae?pvs=105
applicationUrl: https://www.oikos-stgallen.com/open-positions-oikos-solar
linkedin: https://www.linkedin.com/company/oikos-solar/
instagram: https://www.instagram.com/oikos_solar/
addressLines: |-
  oikos Solar, c/o oikos St. Gallen
  Dufourstrasse 50
  9000 St. Gallen
officeNote: Containers behind the HSG library.
